-- Creating the Orders Table, with PK as Order_ID
CREATE TABLE Orders(
	order_id int PRIMARY KEY,
	date Date,
	time Time
);

SELECT * FROM Orders

-- Creating the Pizza Types table with PK as Pizza_type_ID
CREATE TABLE Pizza_Types(
	pizza_type_id Varchar PRIMARY KEY,
	name Varchar,
	category Varchar,
	ingredients Text
)

SELECT * FROM pizza_types

-- Creating Pizza Table with PK as Pizza_ID and FK as Pizza_Type_ID
CREATE TABLE Pizzas(
	pizza_id varchar PRIMARY KEY,
	pizza_type_id varchar,
	size varchar,
	price decimal,
	FOREIGN KEY (Pizza_type_id) REFERENCES Pizza_types(pizza_type_id)
);

SELECT * FROM pizzas

-- Creating Order_details Table with two FK, order_id and pizza_id
CREATE TABLE Order_details(
	order_details_id int,
	order_id int,
	pizza_id varchar,
	quantity int,
	FOREIGN KEY (order_id) REFERENCES orders(order_id),
	FOREIGN KEY (pizza_id) REFERENCES pizzas(pizza_id)
)

SELECT * FROM Order_details

/* 
	KPI'S
	1. Total Revenue
	2. Average Order Value
	3. Total Pizzas Sold
	4. Total Orders
	5. Average Pizza per Order

	QUESTIONS TO ANSWER
	1. Daily Trends for Total Orders
	2. Hourly Trend for Total Orders
	3. Percentage of Sales by Pizza Category
   	4. Percentage of Sales by Pizza Size
   	5. Total Pizza Sold by Pizza Category
   	6. Top 5 Best Sellers by Total Pizza Sold
   	7. Bottom 5 Worst Sellers by Total Pizza Sold
*/

/* 	Total Revenue (We need the total revenue generated by the company,
	so we need to multiply the price of each pizza by the quantity for each order) */
SELECT 
	SUM(quantity * Price) AS Total_Revenue_Generated
FROM Pizzas AS P
	RIGHT JOIN order_details AS OD
	ON P.pizza_id = OD.pizza_id;

-- Average Order Value (This is the Total Order Value / Order Count)
SELECT 
	ROUND (SUM (quantity * Price) / COUNT(DISTINCT Order_ID), 2) AS Average_Order_Value
FROM Pizzas AS P
	RIGHT JOIN order_details AS OD
	ON P.pizza_id = OD.pizza_id;

-- Total Pizzas Sold (This is the Sum of all pizza sold)
SELECT SUM(Quantity) AS Total_Pizzas_Sold
FROM order_details;

-- Total Orders (This is the total number of orders made)
SELECT COUNT(Order_id) AS Total_Orders
FROM orders;

-- Average Pizza per Order (This is the total number of pizzas divided by the number of orders)
SELECT SUM(Quantity) / COUNT(DISTINCT order_id) AS Average_Pizza_Per_Order 
FROM Order_details;

-- Daily Trends for Total Orders (How many orders were made per day of the week)
SELECT 
	TRIM(TO_CHAR(date, 'Day')) AS Day_of_the_week,
	COUNT(DISTINCT Order_id) AS Total_Orders
FROM Orders
GROUP BY Day_of_the_week
ORDER BY Total_Orders DESC;

-- Hourly Trend for Total Orders (How many orders were made in each hour)
SELECT
	EXTRACT(HOUR FROM time ) AS Hour,
	COUNT(DISTINCT Order_id) AS Total_Orders
FROM Orders
GROUP BY Hour
ORDER BY Total_Orders;

/* Percentage of Sales by Pizza Category (I will calculate the Total Revenue per category,
   then divide it by the Total Revenue Generated then multiplied by 100) */
SELECT 
	Category, SUM(quantity * Price) AS Revenue_per_category,
	SUM(Quantity * Price) /
	(SELECT SUM(Quantity * Price)
	FROM Pizzas AS P2
	JOIN Order_details AS OD2
	ON OD2.pizza_id = P2.pizza_id) * 100 AS Percentage_Sales
FROM Pizzas AS P
RIGHT JOIN Pizza_types AS PT
	ON P.pizza_type_id = PT.pizza_type_id
RIGHT JOIN order_details AS OD
	ON OD.pizza_id = P.pizza_id
GROUP BY Category
ORDER BY Percentage_Sales DESC;

/* Percentage of Sales by Pizza Size 
   Percentage of Sales by Pizza Size (I will calculate the Total Revenue per category,
   then divide it by the Total Revenue Generated then multiplied by 100) */
SELECT 
	Size, SUM(quantity * Price) AS Revenue_per_category,
	SUM(Quantity * Price) /
	(SELECT SUM(Quantity * Price)
	FROM Pizzas AS P2
	JOIN Order_details AS OD2
	ON OD2.pizza_id = P2.pizza_id) * 100 AS Percentage_Sales
FROM Pizzas AS P
RIGHT JOIN Pizza_types AS PT
	ON P.pizza_type_id = PT.pizza_type_id
RIGHT JOIN order_details AS OD
	ON OD.pizza_id = P.pizza_id
GROUP BY Size
ORDER BY Percentage_Sales DESC;


-- Total Pizza Sold by Pizza Category (This is the total pizza sold for each category)
SELECT Category, SUM(Quantity) AS Quantity_Sold
FROM Pizzas AS P
RIGHT JOIN Pizza_types AS PT
	ON P.pizza_type_id = PT.pizza_type_id
RIGHT JOIN order_details AS OD
	ON OD.pizza_id = P.pizza_id
GROUP BY Category
ORDER BY Quantity_Sold DESC;


-- Top 5 Best Sellers by Total Pizza Sold (This is the Top 5 best sellers in the company by the number of pizzas sold)
SELECT Name, SUM(Quantity) AS Total_Pizzas_Sold
FROM Pizzas AS P
RIGHT JOIN Pizza_types AS PT
	ON P.pizza_type_id = PT.pizza_type_id
RIGHT JOIN order_details AS OD
	ON OD.pizza_id = P.pizza_id
GROUP BY Name
ORDER BY Total_Pizzas_Sold DESC
LIMIT 5;

--Bottom 5 Worst Sellers by Total Pizza Sold (This is the Bottom 5 best sellers in the company by the number of pizzas sold)
SELECT Name, SUM(Quantity) AS Total_Pizzas_Sold
FROM Pizzas AS P
RIGHT JOIN Pizza_types AS PT
	ON P.pizza_type_id = PT.pizza_type_id
RIGHT JOIN order_details AS OD
	ON OD.pizza_id = P.pizza_id
GROUP BY Name
ORDER BY Total_Pizzas_Sold ASC
LIMIT 5;